version: '3'

services:
  webdb:
    image: mariadb:10.4
    #command: >
    #  sh -c "/usr/sbin/mariadbd --user=root && echo 'Starting mysql...'"
    command: [--innodb-log-file-size=16M,--max-allowed-packet=1G]
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=root
    volumes:
      - ./data/:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - webapp-network

  webapp:
    build:
      context: .
    #command: >
    #  sh -c "composer update"
    ports:
      - '8000:8000'
    environment:
      - VIRTUAL_HOST=localhost
    depends_on:
      - webdb
    volumes:
      - '.:/var/www/html'
    networks:
      - webapp-network

  #front:
  #  buil:d:
  #    co:ntext: .
  #    do:ckerfile: DockerNodefile
  #  port:s:
  #    - :'8000:8000'
  #  envi:ronment:
  #    - :VIRTUAL_HOST=localhost
  #  depe:nds_on:
  #    - :db
  #  volu:mes:
  #    - :'.:/var/www/html'
  #  netw:orks:
  #    - :app-network

networks:
  webapp-network:
    driver: bridge
